README.md
=> docs: make CLI more prominent in main README

README.md
Updates README with how to run tests, and the potential need to bootstrap web-scripts.
=> docs: Updates doc with how to run tests

packages/create-web-scripts-library/package.json, packages/create-web-scripts-library/src/cli.ts, packages/create-web-scripts-library/src/index.ts
we incorrectly implemented the logs using the debug project. We need all of the log messages to
appear for this project.
=> fix(create-web-scripts-library): make sure that log output is shown

packages/web-scripts/config/jest.config.js
=> fix(web-scripts): ignore TypeScript declaration files from coverage

package.json, packages/web-scripts/src/SharedTypes.ts, packages/web-scripts/src/Tasks/LintTask.ts, packages/web-scripts/src/index.ts, packages/web-scripts/src/integration.test.ts, yarn.lock
Due to some issues with the CI setup for lerna publish, I'm forced to retry publishing the package with this update included.
=> feat(web-scripts): add checkstyle to lint

package.json, packages/eslint-config-typescript/package.json, packages/eslint-config/package.json, yarn.lock
BREAKING CHANGE: Major version bump
=> fix(eslint-config): Update typescript-eslint packages to ^2.2.0

packages/create-web-scripts-library/package.json, packages/eslint-config-base/package.json, packages/eslint-config-react/package.json, packages/eslint-config-typescript/index.js, packages/eslint-config-typescript/package.json, packages/eslint-config/package.json, packages/prettier-config/package.json, packages/tsconfig/package.json, packages/web-scripts-utils/package.json, packages/web-scripts/package.json, packages/web-scripts/src/integration.test.ts, yarn.lock
=> feat(web-scripts): Upgrade to ESLint ^6.8.0

.dependabot/config.yml, README.md, packages/create-web-scripts-library/package.json, packages/create-web-scripts-library/src/index.ts, packages/web-scripts-utils/src/has-config.ts, packages/web-scripts/src/SharedTypes.ts, packages/web-scripts/src/Tasks/AuditTasks/__fixtures__/0/package.json, packages/web-scripts/src/Tasks/AuditTasks/__fixtures__/12/package.json, packages/web-scripts/src/Tasks/AuditTasks/__fixtures__/30/package.json, packages/web-scripts/src/Tasks/AuditTasks/index.test.ts, packages/web-scripts/src/Tasks/AuditTasks/index.ts, packages/web-scripts/src/Tasks/PostinstallTasks/__fixtures__/0/package.json, packages/web-scripts/src/index.ts, postinstall.sh
=> feat(web-scripts): rename postinstall to audit

packages/web-scripts/src/SharedTypes.ts, packages/web-scripts/src/Tasks/FormatTask/__fixtures__/poorly-formatted-file.ts, packages/web-scripts/src/Tasks/FormatTask/index.test.ts, packages/web-scripts/src/Tasks/FormatTask/index.ts, packages/web-scripts/src/Tasks/LintTask.ts, packages/web-scripts/src/index.ts
=> fix(web-scripts): get format working, add test

postinstall.sh
should make cloning for new contributors better.
=> build: add a postinstall step to init submodules

package.json, packages/create-web-scripts-library/package.json, packages/eslint-config-base/package.json, packages/eslint-config-react/package.json, packages/eslint-config-typescript/package.json, packages/eslint-config/package.json, packages/prettier-config/package.json, packages/tsconfig/package.json, packages/web-scripts-utils/package.json, packages/web-scripts/config/lint-staged.config.js, packages/web-scripts/package.json, packages/web-scripts/src/@types/index.d.ts, packages/web-scripts/src/SharedTypes.ts, packages/web-scripts/src/Tasks/CommitTasks.ts, packages/web-scripts/src/Tasks/LintTask.ts, packages/web-scripts/src/index.ts, yarn.lock
=> feat(web-scripts): fix lint-staged usage for latest version

packages/web-scripts-utils/tsconfig.json, packages/web-scripts/config/tsconfig.json, packages/web-scripts/package.json, packages/web-scripts/src/integration.test.ts, packages/web-scripts/tsconfig.json, yarn.lock
A few issues related to ts-jest and TypeScript updates that needed fixin'!
fixes #224 , fixes #215
=> Fix issues that are causing the build to fail

packages/eslint-config-base/es5.js
Enable https://eslint.org/docs/rules/no-unsafe-finally
Fixes #229
=> feat(eslint-config-base): add rule for diabling unsafe finally blocks

packages/web-scripts/src/Tasks/AuditTasks/index.test.ts
the test fails frequently, as the connection to the auditing service seemingly gets throttled as we
do so many in parallel. Instead, lets just mock it to avoid blocking PRs in annoying ways.
=> test(web-scripts): mock network for web-scripts audit

.github/workflows/rebase.yml, .github/workflows/test.yml, packages/eslint-config-react/index.js, packages/eslint-config-react/package.json, packages/eslint-config/package.json, packages/web-scripts/src/Tasks/AuditTasks/index.test.ts, packages/web-scripts/src/integration.test.ts, yarn.lock
Adds the plugin to eslint-config-react-hooks and to the appropriate packages and test files.
#305
=> improvement(eslint-config-react): adds eslint-plugin-react-hooks plugin

packages/web-scripts/package.json, packages/web-scripts/src/integration.test.ts, yarn.lock
they seem to have fixed the issues in ts-jest which were causing issues for us.
Fixes #296, #297
=> build: ts-jest to 25.4.0; drop jest-config

packages/eslint-config-typescript/index.js, packages/eslint-config-typescript/package.json, packages/eslint-config/package.json, yarn.lock
=> upgrade to latest to support type export syntax 

.github/workflows/test.yml, README.md, packages/eslint-config/index.js, packages/eslint-config/package.json, packages/eslint-plugin/.eslintrc.json, packages/eslint-plugin/README.md, packages/eslint-plugin/package.json, packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/best-practices/no-discouraged-words.md, packages/eslint-plugin/src/rules/best-practices/no-discouraged-words.test.ts, packages/eslint-plugin/src/rules/best-practices/no-discouraged-words.ts, packages/eslint-plugin/src/util/helpers.ts, packages/eslint-plugin/src/util/testHelpers.ts, packages/eslint-plugin/tsconfig.json, yarn.lock
This is a working branch of the upcoming 9.0 release. It contains the following changes:
- Set `@spotify/best-practices/no-discouraged-words` to `error`
=> merge bih/release-9.0 into spotify/release-9.0

.github/workflows/dev-publish.yml, .github/workflows/rc-publish.yml
merging this into master so that new branches contain the canary deployment logic
=> ci: enable canary releases from canary branch

README.md
update versions in example bc people copy/paste
=> docs(README): update versions in example

packages/web-scripts/README.md
BREAKING CHANGE: Trigger v11 release
=> chore(web-scripts): trigger v11 release

CHANGELOG.md
While battling the publishing issues, the changelog accumulated bunch of erroneous updates. This fixes that
=> docs(changelog): manual changelog update

release.sh
BREAKING CHANGE: v14 borked, unpublished, must use v15
=> fix(web-scripts): v14 borked, unpublished, must use v15

packages/web-scripts/config/lint-staged.config.js
fix(precommit): add in --passWithNoTests flag to enable precommit hook to succeed with no tests
#1020
=> fix(precommit): add in --passWithNoTests flag to test step

package.json, packages/eslint-plugin/package.json, packages/tsconfig/package.json, packages/web-scripts/package.json, yarn.lock
Reverts spotify/web-scripts#1094
=> Revert "build(deps): update min typescript version to 4.5.0"

package.json, packages/eslint-plugin/package.json, packages/tsconfig/package.json, packages/web-scripts/package.json, yarn.lock
Duplicating work from https://github.com/spotify/web-scripts/pull/1094, see context there for original changes.
This PR is rebased on master which recently got some dependency upgrades, so test failures are fixed :D
=> build(deps): upgrade typescript min version to 4.5.0
