- README.md
- packages/web-scripts/README.md
- packages/web-scripts/package.json
- packages/web-scripts/src/index.ts
- packages/web-scripts/src/integration.test.ts
Pardon our dust! `fix` was meant to be dropped before open-sourcing in favor of the clarified and
revamped `precommit`. It's not documented, and would only have been visible if you ran `web-scripts
--help`. In the future this would obviously be a major version, but I'd like to avoid bumping to
2.0.0 three days after open sourcing.
> fix(web-scripts): drop the `fix` command

- .travis.yml
- packages/eslint-config-base/package.json
- packages/eslint-config-react/package.json
- packages/eslint-config-typescript/package.json
- packages/prettier-config/package.json
- packages/tsconfig/package.json
- packages/web-scripts/package.json
- Update `engines` fields
- Remove node 8 from Travis config
> Drop support for node v8

- README.md
Folks probably want to know how to use it as soon as possible when evaluating a project, so I figured it was best to put that link even higher.
> Provide the most actionable link up front

- .gitignore
- .gitmodules
- .travis.yml
- packages/create-web-scripts-library/README.md
- packages/create-web-scripts-library/bin/create-web-scripts-library
- packages/create-web-scripts-library/package.json
- packages/create-web-scripts-library/src/cli.ts
- packages/create-web-scripts-library/src/get-install-cmd.ts
- packages/create-web-scripts-library/src/index.ts
- packages/create-web-scripts-library/src/integration.test.ts
- packages/create-web-scripts-library/src/messages.ts
- packages/create-web-scripts-library/tsconfig.json
- packages/web-scripts/.gitignore
- packages/web-scripts/src/integration.test.ts
- yarn.lock
**Why**: in lieu of an `init` script like Storybook does, this simpler path to create a scaffolded app using https://github.com/spotify/web-scripts-library-template in the style of create-next-app or create-react-app. This also means you don't need to ship any of the scaffolding deps (such as fs-extra) with web-scripts.
Fixes #11
> feat(create-web-scripts-library): implement cli and script

- packages/create-web-scripts-library/package.json
**Why**: noticed when using this through things like `npx` and `yarn create` install all of the web-scripts dependencies, which it definitely doesn't need to do.
>  fix(create-web-scripts-library): move web-scripts to devDependency 

- packages/web-scripts/config/jest.config.js
- packages/web-scripts/config/lint-staged.config.js
- packages/web-scripts/src/Tasks/TestTask.ts
**Why**: rootDir, coverageDirectory, and collectCoverageFrom were all configured by providing
non-overrideable values in the CLI invocation arguments. This moves those values into the base
config, which we encourage people to spread over for their custom configuration.
fix #19
> fix(web-scripts): allow all test options to be configured

- packages/web-scripts/README.md
Not sure this is the best place to put these (for example, should we instead place a default .travis.yml in the template repo?), as they are verbose. I wish there were a way to automate this stuff. But at least having it consolidated in a single place is better than having to search various docs + the internet tutorials.
> Add instructions for setting up semantic-release on travis

- README.md
Reduce ambiguity between `@spotify/web-scripts` and just `web-scripts` (which also exists in npm registry)
> docs: Update README to have the package name

- package.json
- packages/web-scripts/src/index.ts
- yarn.lock
https://www.npmjs.com/advisories/1012
https://www.npmjs.com/advisories/1013
https://www.npmjs.com/advisories/1014
https://www.npmjs.com/advisories/1065
Originally I attempted to upgrade all dependencies in this PR, but eslint 6 changed (it seems) how they load plugins / config, which caused at least the integration test to fail. I haven't evaluated if this means real-world failures yet.
Wanted to get the vulnerabilities fixes in without delaying further.
> fix(deps): fix vulnerabilities

- package.json
- packages/eslint-config-base/package.json
- packages/eslint-config-react/package.json
- packages/eslint-config-typescript/package.json
- packages/prettier-config/package.json
- packages/tsconfig/package.json
- packages/web-scripts/package.json
Adding repository links in `package.json` will make this repo more discoverable (since it adds a link at  https://www.npmjs.com/package/@spotify/web-scripts). Marked as a fix to trigger a publish.
> fix: Add repostiory field to package.json files

- packages/eslint-config-react/README.md
Hey there 👋! 
Saw that the `eslint-plugin-jsx-a11y` is required for the `eslint-config-react` web script so updated the README docs accordingly.
> fix(eslint-config-react): Update eslint-config-react README

- packages/tsconfig/docs/examples.md
The existing `tsconfig.app.json` rule for `noEmit: true` will break compilation if used with `ts-loader` as instructed in `examples.md`.
This is likely because `tsconfig.app.json` was originally taken from [Microsoft's instructions](https://github.com/microsoft/TypeScript-Babel-Starter) for Webpack setups that use `babel-loader`, and the instructions for `ts-loader` were taken from [Webpack's guide on TypeScript](https://webpack.js.org/guides/typescript/).
I've clarified the `examples.md` so that either method can be used without errors.
> Clarify tsconfig webpack instructions

- .github/workflows/publish.yml
- package.json
- release.sh
I wanted to use https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump to accomplish this, but it outputs "patch" for any commit, which is not what we want; we want non-releasing commits to be ignored for publishing.
> ci: publish using CI with Github Actions

- package.json
- packages/web-scripts/src/SharedTypes.ts
- packages/web-scripts/src/Tasks/LintTask.ts
- packages/web-scripts/src/index.ts
- packages/web-scripts/src/integration.test.ts
- yarn.lock
We've been talking about making a few changes to the base behavior of `web-scripts lint`:
1. We would like there to be a build artifact output by ESLint by default. This would help us to assess whether builds ran static analysis without having to do invasive checks.
2. We would like to run typecheks by default as part of linting. This will help us move to using Babel to build if we decide that makes sense eventually; it will also help us avoid needing to run `web-scripts build` to properly test a project, which is a bit unintuitive at the moment.
This PR:
- **adds a type check by default to `web-scripts lint`.** You can turn it off by using `--no-typecheck`.
- **adds a parallel ESLint run which outputs Checkstyle**. Since you can't use two formatters for ESLint, and ESLint forces you to …
> feat(web-scripts): add typechecking to lint task

- packages/eslint-config-typescript/index.js
no-useless-constructor is one of those ESLint rules that fails to work properly in a TS app, like
no-unused-vars. an override must be provided for those using TypeScript.
> fix(eslint-config-typescript): add no-useless-constructor override

- packages/eslint-config-react/index.js
- packages/eslint-config-react/package.json
- yarn.lock
`eslint-plugin-react` was updated (https://github.com/yannickcr/eslint-plugin-react/pull/2408) to support a new `static-variables` option to `react/sort-comp`. With this change, our linting started breaking. After some investigation, it turns out that `statics` seems to refer to some old `React.createClass` option, so static variables actually fell into the check for `static-methods`. Now that is fixed and `static-methods` only check for methods and `static-variables` only check for variables. So it doesn't seem like a breaking change, but we seem to have misused the options a bit.
By only adding `static-variables` to our list we should still support older apps using `React.createClass` (if any), and everything will work again like before.
> fix(eslint-config-react): Add `static-variables` to `react/sort-comp`

- packages/create-web-scripts-library/package.json
- packages/web-scripts-utils/package.json
- packages/web-scripts/package.json
- packages/web-scripts/src/SharedTypes.ts
- packages/web-scripts/src/Tasks/LintTask.ts
- packages/web-scripts/src/index.ts
- packages/web-scripts/src/integration.test.ts
Resolves #72
Work In Progress
This task will run `prettier check` on the `src/` path at the location from which it was called. Prettier will check against a list of files with the extensions `.ts`, `.tsx`, `.js`, `.jsx` then return a subset of these files which do not meet the styling standards for the prettier configuration provided.
Note: As of writing this command does not currently integrate with ESLint intentionally.
_Waiting on implementation feedback_
[`prettier --check`](https://prettier.io/docs/en/cli.html#--check)
> feat(web-scripts lint): optional --stylecheck argument

- .dependabot/config.yml
I'm unsure whether this actually works to dependabot to truly ignore the fixtures.
> build(dependabot): add config for intentional security issues for tests

- packages/web-scripts/__fixtures__/Component.test.jsx
- packages/web-scripts/__fixtures__/Component.test.tsx
- packages/web-scripts/src/integration.test.ts
- yarn.lock
we found that an older version of web-scripts did not support JSX tests out of the box. This test
will ensure that we keep that working.
> test(web-scripts): add a test for tests with jsx

- package.json
- release.sh
- yarn.lock
It was recently noted that we aren't publishing GitHub Releases at the moment; we can easily add them to our Lerna setup using this flag.
> ci: publish GitHub releases automatically via Lerna

- packages/eslint-config-base/es5.js
triple slashes are used in TypeScript declarations. The ESLint rule spaced-comment can interfere
with them, especially when using `--fix`.
fix #117
> fix(eslint-config-base): allow triple slashes

- packages/eslint-config-react/index.js
We are running into an issue with inconsistency throughout our app when it comes to string props and string children of React elements. This rule, as it's set up in this PR, enforces the absence of curly braces for props or children when passing strings.
props: `<App foo="bar" />` is enforced
children: `<App>Foo</App>` is enforced
This rule is auto fixable, so migration should be easy.  Please let me know thoughts on this and the current settings.
This does feel like a code style, but the prettier folks seemed opinionated that this should be handled in linting.  Would love to hear your thoughts :)
https://github.com/prettier/prettier/issues/3303
Documentation: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md
> feat(index.js): Add react/jsx-curly-brace-presence rule

- .github/workflows/publish.yml
- .github/workflows/test.yml
- postinstall.sh
- yarn.lock
this is now handled in the prepare script, and the action was broken anyway, breaking all of our builds.
> update build to unblock releases

- packages/create-web-scripts-library/src/index.ts
When running `yarn create @spotify/web-scripts-library` you end up with a `package.json` that is not nicely formatted (single line JSON string). This should fix that and make the created `package.json` correctly indented 🙂
> fix(create-web-scripts-library): format package.json

- packages/eslint-config-base/README.md
- packages/eslint-config-react/README.md
- packages/eslint-config-typescript/README.md
.eslintrc is deprecated (https://eslint.org/docs/user-guide/configuring)
> docs(eslint-config): rename .eslintrc to .eslintrc.json

- packages/web-scripts/src/Tasks/CommitTasks.ts
fixes #247 
this follows the same pattern as the other configs, inspired by kcd-scripts dynamic config setup.
> feat(web-scripts): allow custom lint-staged

- packages/create-web-scripts-library/package.json
- packages/tsconfig/README.md
- packages/tsconfig/docs/examples.md
- packages/tsconfig/tsconfig.json
- packages/web-scripts-utils/package.json
- packages/web-scripts-utils/tsconfig.json
- packages/web-scripts/package.json
- packages/web-scripts/src/Tasks/BuildTask.ts
- packages/web-scripts/src/Tasks/LintTask.ts
- packages/web-scripts/tsconfig.json
- yarn.lock
`noEmit` interferes with many recent flags added to tsc, such as `incremental`. we've decided it
will be best to configure `noEmit` directly on the commands where we know it's needed, such as
linting and building, using cli arguments, and to leave it out of the tsconfigs. this should make
testing and webpacking much simpler with our configs.
BREAKING CHANGE: your builds will potentially produce artifacts at unexpected times depending on
your local tscsonfig.json
fixes #252
> fix: remove `noEmit` default value

- packages/create-web-scripts-library/package.json
- packages/web-scripts/package.json
- packages/web-scripts/src/integration.test.ts
- yarn.lock
BREAKING CHANGE: running web-scripts without arguments exits code 1 now instead of exiting 0
> build(web-scripts): use commander 5

- packages/web-scripts/src/index.ts
- packages/web-scripts/src/integration.test.ts
Upgrading `commander.js` to 5.x resulted in unknown options being parsed twice, breaking tasks in some scenarios.
For more details: tj/commander.js#1138
> Fix duplicated web scripts options

- packages/web-scripts/src/index.ts
- packages/web-scripts/src/integration.test.ts
the best test case for this is `web-scripts test filename`, which currently doesn't work.
positional args were not making there way through to the web-scripts commands, because commander 5 changed how we need to handle args. there is now conveniently an `args` array on the command which contains all args (positional or flagged) in order, which seems to be more reliably correct from what the user inputs compared to using the `parseOptions(process.argv)` method.
> fix(web-scripts): positional args were being stripped out

- packages/eslint-config-typescript/index.js
the new naming-convention config flunked many linters. for now, we will disable the config and
re-evaluate whether something that better matches our methodology can be used instead.
> fix(eslint-config-typescript): turn off naming-convention

- packages/eslint-config-react/package.json
- yarn.lock
Version 3 of `eslint-plugin-react-hooks` is only compatible with eslint 6 and below, and this project depends on eslint 7. Version 4 of `eslint-plugin-react-hooks` supports eslint 7.
Version 4 is already specified in `devDependencies`, so this was likely left by mistake.
> fix(eslint-config-react): fix peer dependency on eslint-plugin-react-hooks

- .github/workflows/test.yml
- README.md
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- packages/eslint-plugin/.eslintrc.json
- packages/eslint-plugin/README.md
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/index.ts
- packages/eslint-plugin/src/rules/best-practices/no-discouraged-words.md
- packages/eslint-plugin/src/rules/best-practices/no-discouraged-words.test.ts
- packages/eslint-plugin/src/rules/best-practices/no-discouraged-words.ts
- packages/eslint-plugin/src/util/helpers.ts
- packages/eslint-plugin/src/util/testHelpers.ts
- packages/eslint-plugin/tsconfig.json
- yarn.lock
To help support the shift towards more inclusive wording in our software, which is a simple yet impactful change for the Spotify R&D community to make, I have been investigating how to encourage such a shift in the web community. Currently, it covers two words in the community that we should phase out - blacklist and whitelist - and naturally over time this list will (and should) be expected to grow.
For this reason, I'm thinking it makes the most sense as an ESLint plugin. That's what this PR proposes.
- ESLint is popular, and used already by the Spotify community.
- It has plenty of support across many code editors, including Visual Studio Code. This makes it easier to use during development (rather than retroactively renaming variables).
- It can be gradually rolled out across …
> Implement ESLint rule for "discouraged words" in our codebases

- package.json
- packages/tsconfig/package.json
- packages/tsconfig/tsconfig.json
- packages/web-scripts/package.json
- yarn.lock
BREAKING CHANGE: must upgrade to TypeScript 4 as a consumer; new tsconfig takes advantage of
incremental + noEmit
fix #487, #252
> feat: use TypeScript 4

- packages/eslint-config-typescript/index.js
- packages/eslint-config-typescript/package.json
- packages/eslint-config/package.json
- packages/eslint-plugin/package.json
- yarn.lock
Closes #555.
Having different versions of `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin` seems to cause false positives like the one described in #555. This commit syncs the versions which appears to resolve the issue.
> fix: sync @typescript-eslint versions across repo

- package.json
- packages/create-web-scripts-library/package.json
- packages/eslint-config-typescript/index.js
- packages/eslint-config-typescript/package.json
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- packages/eslint-plugin/package.json
- packages/tsconfig/package.json
- packages/tsconfig/tsconfig.json
- packages/web-scripts/package.json
- yarn.lock
This is a working branch of the upcoming 9.0 release. It contains the following changes:
- Set @spotify/best-practices/no-discouraged-words to error
- Use TypeScript 4.0
> Release 9.0

- packages/web-scripts/config/jest.config.js
The `tsConfig` option was deprecated in [ts-jest@26.4.2](https://github.com/kulshekhar/ts-jest/blob/5a7009e9f475ae5676ca52a59039fa9549a4f4f7/CHANGELOG.md#deprecations) in favor of `tsconfig`. 
This should get rid of warnings like this,
> fix: update ts-jest config

- packages/eslint-config-base/es5.js
It is recommended to disable `no-undef` in TypeScript projects, as documented here:
[We strongly recommend that you do not use the no-undef lint rule on TypeScript projects. The checks it provides are already provided by TypeScript without the need for configuration - TypeScript just does this significantly better.](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors)
> Disable no-undef

- package.json
- packages/eslint-config-base/es5.js
- packages/eslint-config-react/index.js
- yarn.lock
It is recommended to disable `no-undef` in TypeScript projects, as documented here:
[We strongly recommend that you do not use the no-undef lint rule on TypeScript projects. The checks it provides are already provided by TypeScript without the need for configuration - TypeScript just does this significantly better.](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors)
> fix: disable no-undef

- packages/web-scripts/src/index.ts
The `precommit` command in web-scripts currently destructures the opts [like so](https://github.com/spotify/web-scripts/blob/b6469e5a6a84b389145576bba56adf70194f1c98/packages/web-scripts/src/index.ts#L145-L151):
```
const {
tests,
typecheck,
'jest-config': jestConfig,
'eslint-config': eslintConfig,
'prettier-config': prettierConfig,
} = getOpts(cmd);
```
The latter three are undefined as the hyphenated names do not exist in the command opts. This PR fixes this with the following:
```
const {
tests,
typecheck,
jestConfig,
eslintConfig,
prettierConfig,
} = getOpts(cmd);
```
> fix: precommit opts destructuring

- packages/web-scripts/src/SharedTypes.ts
- packages/web-scripts/src/Tasks/CommitTasks.ts
- packages/web-scripts/src/index.ts
This PR adds support for using Husky v6. An additional parameter `--edit` was added in order to be able to pass along the information provided by Husky. If the `--edit` option isn't set, the fallback is `HUSKY_GIT_PARAMS`. This ensures backwards compatibility with current setups.
It is possible to pass along the `--edit` parameter, as follows:
```bash
yarn web-scripts commitmsg --edit=$1
```
Here, `$1` is the variable provided by Husky, and it points to the last commit message from the specified file. Whilst this works, it isn't clear that one can add the `--edit` parameter.
When running the following command (as specified in the README file), the installed version of Husky is 6.0.0.
```bash
yarn add --dev @spotify/web-scripts husky
```
This version …
> feat(husky): add support for Husky v6

- release.sh
The release script determines if a publish should happen using a dry run of semantic release to determine if the commits contain publishable changes (feat, bug, breaking change).
If true, the release script uses lerna to publish, however, lerna has its own logic for determining whether to publish, specifically running a git diff in each package. It will exclude markdown files, tests, etc, so an attempt to force a version bump with an empty commit or readme tweak will fail:
Example
```
$ ./release.sh
spotify/web-scripts: Running semantic-release in --dry-run to see if we should trigger a lerna release.
[4:03:31 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is major
spotify/web-scripts: A release will be triggered.
spotify/web-scripts: …
```
> ci(lerna): fix lerna publish

- packages/eslint-config-typescript/index.js
See https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md - only added added as a warning so as not to be a breaking change. Seems like an uncontroversial addition but happy to hear otherwise 👍
> Add no-floating-promises to TS config

- packages/eslint-config-typescript/index.js
Reverts spotify/web-scripts#907
Introducing this new rule causes ESLint to fail with the following error:
```
Error: Error while loading rule '@typescript-eslint/no-floating-promises': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```
Removing from this release so that it doesn't block
> Revert "Add no-floating-promises to TS config"

- packages/web-scripts/src/Tasks/BuildTask.ts
Thanks @yuriteixeira for spotting this bug where we output declarations for directories we don't need.
> fix: do not output type declarations for cjs/esm

- package.json
- packages/eslint-plugin/package.json
- packages/tsconfig/package.json
- packages/web-scripts/package.json
- yarn.lock
Updated the minimum typescript version from 4.2.3 to 4.5.0 in all relevant packages.
**Context:**
The current major version of Encore Web (v6) requires Typescript v4.5.0 or higher. 
Because most encore-web customers get Typescript transitively through web-scripts, encore-web is unable to use a peerDependency to communicate to customers when their Typescript version is too old. If we were to add a `typescript: ^4.5.0` peerDep, encore-web customers getting typescript from web-scripts would see an incorrect/irrelevant "unmet peer dependency" warning that they can't rectify.
An easy solution is to bump the min TS version in web-scripts, likely followed by a fleetshift prompting encore-web customers to upgrade to the latest web-scripts. There's a [precedent for bumping web-scripts typescript …
> build(deps): update min typescript version to 4.5.0

- package.json
- packages/web-scripts/package.json
- yarn.lock
Dump `lerna`, `commitizen`, and `semantic-release` dependencies to address security vulnerabilities.
> fix: bump `lerna`, `commitizen`, and `semantic-release` deps
